project_name: lego

release:
  name_template: 'Release {{.Tag}}'
  draft: true

before:
  hooks:
    - go mod download

builds:
  - env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    ldflags: "-s -w -X github.com/vseinstrumentiru/lego/v2/version.Version={{ .Version }} -X github.com/vseinstrumentiru/lego/v2/version.CommitHash={{ .ShortCommit }} -X github.com/vseinstrumentiru/lego/v2/version.BuildDate={{ .Date }}"
    main: ./gen/cmd/lego/main.go
    goos:
      - linux
      - darwin
    goarch:
      - amd64

archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

changelog:
  skip: true

checksum:
  name_template: 'checksums.txt'
