style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/vseinstrumentiru/lego
options:
  commits:
     filters:
       Type:
         - fix
         - fixed
         - Fix
         - added
         - add
         - refactor
         - feat
         - chore
         - deprecated
  commit_groups:
    sort_by: Title
    title_maps:
      fix: Bug Fixes
      fixed: Bug Fixes
      Fix: Bug Fixes
      chore: Chores
      refactor: Chores
      deprecated: Deprecations

      added: Features
      add: Features
      feat: Features
    #   feat: Features
    #   fix: Bug Fixes
    #   perf: Performance Improvements
  header:
    pattern: "^(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
